import type { AutomationPlaybook } from "../../shared/automationPlaybooks";

export const METAPI_OPS_PLAYBOOKS: AutomationPlaybook[] = [
  {
    id: "register_relay_site",
    title: "收录中转站",
    description: "把当前打开的新中转站收录进本地 Metapi：建站点、取系统访问令牌/用户ID、验证并添加连接。已有站点直接返回。",
    tags: ["Metapi", "中转站", "收录", "New API", "签到准备"],
    source: "skill",
    defaultEnabled: true,
    risk: "high",
    recommendedCapabilities: ["observe_page", "operate_page", "deliver_result"],
    selectionHints: ["收录中转站", "收录站点", "添加中转站", "register relay", "metapi 收录"],
    prompt: [
      "任务策略：收录中转站（仅新站）",
      "目标：把当前浏览器页面所属的新中转站收录到本地 Metapi 管理端，并绑定系统访问令牌连接。",
      "工具边界（硬性）：",
      "1. Metapi 管理 API 一律使用本地 API 工具 metapi_*（扩展后台 fetch / src/skills/metapi-ops/scripts）。禁止用浏览器打开/请求 127.0.0.1:4000 或 METAPI_ADMIN_BASE_URL。",
      "2. 浏览器自动化只用于中转站页面取证：系统访问令牌、用户 ID、登录态；不用于发送 Metapi 管理请求。",
      "业务规则：",
      "1. 站点 URL 优先取当前受控页面 URL，但必须规范为站点源站（origin）：只保留 scheme+host(+port)，去掉 /profile、/console、/v1 等路径、query 和 hash。例如 https://example.com/profile → https://example.com。",
      "2. 若用户参数里出现“开启系统代理/启用系统代理”，创建站点时 useSystemProxy=true。",
      "3. 站点名来自参数（如 gpt(name) 或 name=gpt）；缺省可用页面标题（简洁）。",
      "4. 先 metapi_list_sites(url=当前URL)。已存在则立即停止并返回 SITE_EXISTS（siteId/name/url），不要 verify，不要 create account。",
      "5. 新站顺序：",
      "   a) metapi_detect_site(url)",
      "   b) metapi_create_site(name,url,platform?,useSystemProxy?)",
      "   c) 浏览器：个人资料→安全→访问令牌 读取系统访问令牌；头像旁读取用户 ID",
      "   d) metapi_verify_account_token(siteId, accessToken, platformUserId?, credentialMode=session)",
      "   e) 成功后 metapi_create_account → POST /api/accounts {siteId,accessToken,platformUserId?,credentialMode:session,skipModelFetch:false}",
      "6. accessToken=系统访问令牌；不要用 sk- API Key 当可签到连接。platformUserId 是独立字段。",
      "7. 未配置管理令牌时，先 metapi_configure(authToken, baseUrl?)。",
      "8. 失败给出可操作原因；最终回复不回显令牌全文。",
      "同包脚本（调试同源 API，不经浏览器）：src/skills/metapi-ops/scripts/*",
    ].join("\n"),
  },
  {
    id: "start_all_checkin",
    title: "开始签到",
    description: "触发 Metapi 全部签到任务，并读取签到日志汇总成功/失败/跳过。",
    tags: ["Metapi", "签到", "checkin", "巡检"],
    source: "skill",
    defaultEnabled: true,
    risk: "medium",
    recommendedCapabilities: ["deliver_result"],
    selectionHints: ["开始签到", "全部签到", "启动签到", "签到巡检", "checkin"],
    prompt: [
      "任务策略：开始签到（全部）",
      "目标：调用 Metapi 管理 API 启动全部签到，并汇总结果。",
      "硬性边界：",
      "1. 签到触发与日志一律使用 metapi_* 本地 API 工具（后台 fetch）。禁止浏览器去请求 127.0.0.1:4000。",
      "2. 本策略不要求浏览器操作页面；浏览器补签由 /补签 策略处理。",
      "执行顺序：",
      "1) 若未配置管理令牌，先提示配置或调用 metapi_configure。",
      "2) metapi_trigger_checkin（可选 waitSeconds=20~60，便于任务先跑一阵）。",
      "3) metapi_get_checkin_logs(limit=100) 或 metapi_summarize_checkin_logs(limit=100, jobId?)。",
      "4) 输出清晰表格/分组：success / failed / skipped / other，以及 repairCandidates（失败+跳过且有 siteUrl）。",
      "5) 若仍有很多 pending/running，说明“任务仍在进行，可稍后 /补签 或再查日志”。",
      "6) 最终不要回显 token/密钥。",
    ].join("\n"),
  },
  {
    id: "repair_failed_checkin",
    title: "补签",
    description: "根据签到日志找出失败/跳过站点，用浏览器打开并点击签到/立即签到进行补签。",
    tags: ["Metapi", "补签", "浏览器", "签到失败"],
    source: "skill",
    defaultEnabled: true,
    risk: "high",
    recommendedCapabilities: ["observe_page", "operate_page", "deliver_result"],
    selectionHints: ["补签", "签到失败", "跳过补签", "手动签到", "repair checkin"],
    prompt: [
      "任务策略：补签（失败/跳过）",
      "目标：读取 Metapi 签到日志，对 failed + skipped 站点用浏览器自动打开并点击签到。",
      "硬性边界：",
      "1. 读日志/汇总用 metapi_get_checkin_logs 或 metapi_summarize_checkin_logs（后台 fetch）。",
      "2. 浏览器只操作目标中转站页面签到 UI，不要用浏览器请求 Metapi 管理 API。",
      "3. 严禁对“本轮未打开”的站点下结论。未打开的站只能列入 pending_next_batch，不能记 failed/skipped/needs_human。",
      "4. 官方日志里的 failed 只是候选来源，不是浏览器补签结果。",
      "执行顺序：",
      "1) metapi_summarize_checkin_logs(limit=100) 得到 repairCandidates。",
      "2) 若候选为空：报告无需补签。",
      "3) 单次最多实际打开并处理 5 个站点（优先 failed，再 skipped）。",
      "4) 对每个本轮要处理的候选（有 siteUrl）必须完整走完：",
      "   a) browser.new_page 打开 siteUrl（仅 http/https）。记录 page index。",
      "   b) take_snapshot / extract_content 观察；优先：控制台/个人中心/个人资料 → 签到/每日签到/立即签到。",
      "   c) 找到签到按钮则 click；若页面明确显示已签到，则 status=skipped。",
      "   d) 若出现以下任一屏障，立即 status=needs_human，停止该站操作，不要反复点：",
      "      - SHIELD / 我不是机器人 / 安全验证",
      "      - Turnstile / Cloudflare 人机验证 / 五秒盾",
      "      - 图形验证码 / captcha / /checkin/captcha",
      "      - 登录墙 / 需要账号密码",
      "   e) 只有在已打开页面、实际尝试签到后，才能记 status=failed（例如页面明确报错且无验证码）。",
      "   f) 每站结束后立刻 list_pages + close_page 关闭本站临时页。",
      "   g) 立刻 metapi_record_browser_checkin（必须带 siteUrl 与 status，message 写清原因；验证码站写 barrier=captcha/shield）。",
      "5) 处理完本轮最多 5 站后：",
      "   - 汇总本轮真实结果：success / skipped / needs_human / failed",
      "   - 剩余未打开候选列入 pending_next_batch（只列 URL/原因，不记本地结果）",
      "   - 明确提示：再次发送 /补签 继续下一批",
      "6) 不要因为遇到 1-2 个验证码站就停止整批；记录 needs_human 后继续下一个可处理站。",
      "7) 浏览器补签不会自动更新 Metapi 官方签到日志；以本地 metapi_record_browser_checkin 为准。",
      "8) 不要回显任何 token。",
    ].join("\n"),
  },
];
