import type { AutomationPlaybook } from "../../shared/automationPlaybooks";

export const METAPI_OPS_PLAYBOOKS: AutomationPlaybook[] = [
  {
    id: "register_relay_site",
    title: "收录中转站",
    description: "把当前打开的新中转站收录进本地 Metapi：建站点、取系统访问令牌/用户ID、验证并添加连接。已有站点直接返回。",
    tags: ["Metapi", "中转站", "收录", "New API", "签到准备"],
    source: "skill",
    defaultEnabled: true,
    risk: "high",
    recommendedCapabilities: ["observe_page", "operate_page", "deliver_result"],
    selectionHints: ["收录中转站", "收录站点", "添加中转站", "register relay", "metapi 收录"],
    prompt: [
      "任务策略：收录中转站（仅新站）",
      "目标：把当前浏览器页面所属的新中转站收录到本地 Metapi 管理端，并绑定系统访问令牌连接。",
      "工具边界（硬性）：",
      "1. Metapi 管理 API 一律使用本地 API 工具 metapi_*（扩展后台 fetch / src/skills/metapi-ops/scripts）。禁止用浏览器打开/请求 127.0.0.1:4000 或 METAPI_ADMIN_BASE_URL。",
      "2. 浏览器自动化只用于中转站页面取证：系统访问令牌、用户 ID、登录态；不用于发送 Metapi 管理请求。",
      "业务规则：",
      "1. 站点 URL 优先取当前受控页面 URL，但必须规范为站点源站（origin）：只保留 scheme+host(+port)，去掉 /profile、/console、/v1 等路径、query 和 hash。例如 https://example.com/profile → https://example.com。",
      "2. 若用户参数里出现“开启系统代理/启用系统代理”，创建站点时 useSystemProxy=true。",
      "3. 站点名来自参数（如 gpt(name) 或 name=gpt）；缺省可用页面标题（简洁）。",
      "4. 先 metapi_list_sites(url=当前URL)。已存在则立即停止并返回 SITE_EXISTS（siteId/name/url），不要 verify，不要 create account。",
      "5. 新站顺序：",
      "   a) metapi_detect_site(url)",
      "   b) metapi_create_site(name,url,platform?,useSystemProxy?)",
      "   c) 浏览器：个人资料→安全→访问令牌 读取系统访问令牌；头像旁读取用户 ID",
      "   d) metapi_verify_account_token(siteId, accessToken, platformUserId?, credentialMode=session)",
      "   e) 成功后 metapi_create_account → POST /api/accounts {siteId,accessToken,platformUserId?,credentialMode:session,skipModelFetch:false}",
      "6. accessToken=系统访问令牌；不要用 sk- API Key 当可签到连接。platformUserId 是独立字段。",
      "7. 未配置管理令牌时，先 metapi_configure(authToken, baseUrl?)。",
      "8. 失败给出可操作原因；最终回复不回显令牌全文。",
      "同包脚本（调试同源 API，不经浏览器）：src/skills/metapi-ops/scripts/*",
    ].join("\n"),
  },
  {
    id: "start_all_checkin",
    title: "开始签到",
    description: "触发 Metapi 全部签到任务，并读取签到日志汇总成功/失败/跳过。",
    tags: ["Metapi", "签到", "checkin", "巡检"],
    source: "skill",
    defaultEnabled: true,
    risk: "medium",
    recommendedCapabilities: ["deliver_result"],
    selectionHints: ["开始签到", "全部签到", "启动签到", "签到巡检", "checkin"],
    prompt: [
      "任务策略：开始签到（全部）",
      "目标：调用 Metapi 管理 API 启动全部签到，并汇总结果。",
      "硬性边界：",
      "1. 签到触发与日志一律使用 metapi_* 本地 API 工具（后台 fetch）。禁止浏览器去请求 127.0.0.1:4000。",
      "2. 本策略不要求浏览器操作页面；浏览器补签由 /补签 策略处理。",
      "执行顺序：",
      "1) 若未配置管理令牌，先提示配置或调用 metapi_configure。",
      "2) metapi_trigger_checkin（可选 waitSeconds=20~60，便于任务先跑一阵）。",
      "3) metapi_get_checkin_logs(limit=100) 或 metapi_summarize_checkin_logs(limit=100, jobId?)。",
      "4) 输出清晰表格/分组：success / failed / skipped / other，以及 repairCandidates（失败+跳过且有 siteUrl）。",
      "5) 若仍有很多 pending/running，说明“任务仍在进行，可稍后 /补签 或再查日志”。",
      "6) 最终不要回显 token/密钥。",
    ].join("\n"),
  },
  {
    id: "repair_failed_checkin",
    title: "补签",
    description: "根据签到日志找出失败/跳过站点，优先打开外部签到URL或控制台/个人资料，自行完成登录与签到。",
    tags: ["Metapi", "补签", "浏览器", "签到失败"],
    source: "skill",
    defaultEnabled: true,
    risk: "high",
    recommendedCapabilities: ["observe_page", "operate_page", "deliver_result"],
    selectionHints: ["补签", "签到失败", "跳过补签", "手动签到", "repair checkin"],
    prompt: [
      "任务策略：补签（失败/跳过）——必须打开站点找签到入口",
      "目标：对 Metapi 日志 failed/skipped 站，用浏览器真正打开页面并完成签到。",
      "绝对禁止：",
      "1. 禁止只读日志后总结就结束。",
      "2. 禁止因官方日志 HTTP404/fetch failed/签到未启用/Cloudflare403 就不打开。",
      "3. 禁止对未打开的站下结论。",
      "4. 禁止优先去钱包/余额找签到；签到一般在 控制台/个人中心/个人资料/每日签到。",
      "打开哪个 URL：",
      "- 优先 openUrl = externalCheckinUrl（站点已配置的外部签到站）",
      "- 没有外部签到站时再用 siteUrl 根站",
      "- 示例：new-api.abrdns.com → checkin.new-api.abrdns.com；x666.me → up.x666.me",
      "登录规则：",
      "- 若页面未登录/login/expired：优先点击 LinuxDO / Linux.do 登录",
      "- 其次 GitHub 登录",
      "- 完成 OAuth/回调回到站点后，再继续找签到入口",
      "- 不要卡在钱包页；登录后去控制台/个人资料",
      "签到入口路径（按顺序找）：",
      "1) 外部签到页本体（今日签到/立即签到/领取奖励）",
      "2) 控制台 → 个人中心/个人资料/个人设置 → 每日签到/立即签到",
      "3) 顶栏/侧栏：签到、福利、奖励中心、任务与奖励",
      "4) 不要把钱包管理/充值/余额当主路径",
      "验证码：",
      "A. 图形验证码：screenshot 识图 → fill → 确认，最多重试3次",
      "B. SHIELD/我不是机器人：click 复选框本体",
      "C. hCaptcha 图片题：尽量点击正确格子；跨域 iframe 点不到才 needs_human",
      "执行：",
      "1) metapi_summarize_checkin_logs 取 mustOpenThisRound",
      "2) 每个候选必须 new_page(openUrl)",
      "3) take_snapshot → 登录(如需 LinuxDO/GitHub) → 控制台/个人资料找签到 → click",
      "4) close_page + metapi_record_browser_checkin(siteUrl,status必填,message)",
      "5) 有候选时至少 1 次 new_page 才允许最终总结",
      "6) 最终分 openedAndProcessed / pendingNextBatch，禁止把 pending 写成 failed",
      "7) 浏览器补签不改写 Metapi 官方日志",
    ].join("\n"),
  },
];
