import type { AutomationPlaybook } from "../../shared/automationPlaybooks";

export const METAPI_OPS_PLAYBOOKS: AutomationPlaybook[] = [
  {
    id: "register_relay_site",
    title: "收录中转站",
    description: "把当前打开的新中转站收录进本地 Metapi：建站点、取系统访问令牌/用户ID、验证并添加连接。已有站点直接返回。",
    tags: ["Metapi", "中转站", "收录", "New API", "签到准备"],
    source: "skill",
    defaultEnabled: true,
    risk: "high",
    recommendedCapabilities: ["observe_page", "operate_page", "deliver_result"],
    selectionHints: ["收录中转站", "收录站点", "添加中转站", "register relay", "metapi 收录"],
    prompt: [
      "任务策略：收录中转站（仅新站）",
      "目标：把当前浏览器页面所属的新中转站收录到本地 Metapi 管理端，并绑定系统访问令牌连接。",
      "工具边界（硬性）：",
      "1. Metapi 管理 API 一律使用本地 API 工具 metapi_*（扩展后台 fetch / src/skills/metapi-ops/scripts）。禁止用浏览器打开/请求 127.0.0.1:4000 或 METAPI_ADMIN_BASE_URL。",
      "2. 浏览器自动化只用于中转站页面取证：系统访问令牌、用户 ID、登录态；不用于发送 Metapi 管理请求。",
      "业务规则：",
      "1. 站点 URL 优先取当前受控页面 URL，但必须规范为站点源站（origin）：只保留 scheme+host(+port)，去掉 /profile、/console、/v1 等路径、query 和 hash。例如 https://example.com/profile → https://example.com。",
      "2. 若用户参数里出现“开启系统代理/启用系统代理”，创建站点时 useSystemProxy=true。",
      "3. 站点名来自参数（如 gpt(name) 或 name=gpt）；缺省可用页面标题（简洁）。",
      "4. 先 metapi_list_sites(url=当前URL)。已存在则立即停止并返回 SITE_EXISTS（siteId/name/url），不要 verify，不要 create account。",
      "5. 新站顺序：",
      "   a) metapi_detect_site(url)",
      "   b) metapi_create_site(name,url,platform?,useSystemProxy?)",
      "   c) 浏览器：个人资料→安全→访问令牌 读取系统访问令牌；头像旁读取用户 ID",
      "   d) metapi_verify_account_token(siteId, accessToken, platformUserId?, credentialMode=session)",
      "   e) 成功后 metapi_create_account → POST /api/accounts {siteId,accessToken,platformUserId?,credentialMode:session,skipModelFetch:false}",
      "6. accessToken=系统访问令牌；不要用 sk- API Key 当可签到连接。platformUserId 是独立字段。",
      "7. 未配置管理令牌时，先 metapi_configure(authToken, baseUrl?)。",
      "8. 失败给出可操作原因；最终回复不回显令牌全文。",
      "同包脚本（调试同源 API，不经浏览器）：src/skills/metapi-ops/scripts/*",
    ].join("\n"),
  },
  {
    id: "query_model_marketplace_sites",
    title: "查询模型可用站点",
    description: "从 Metapi 模型市场全量接口查询某个模型在哪些站点/渠道可用，并区分精确匹配与本地模糊候选。",
    tags: ["Metapi", "模型", "marketplace", "站点", "查询"],
    source: "skill",
    defaultEnabled: true,
    risk: "low",
    recommendedCapabilities: ["deliver_result"],
    selectionHints: ["模型哪些站点有", "模型在哪些站点", "哪些站点有这个模型", "哪些站点有模型", "模型可用站点", "查询模型站点", "模型市场", "model marketplace", "models marketplace"],
    prompt: [
      "任务策略：查询模型可用站点",
      "目标：查询某个模型在 Metapi marketplace 里哪些站点/渠道可用。",
      "硬性边界：",
      "1. 只使用 metapi_list_model_marketplace_sites 工具；不要用浏览器请求 127.0.0.1:4000。",
      "2. 用户未给模型 ID/名称时，先追问模型；不要猜。",
      "3. 默认 matchMode=auto：先本地 exact，未命中再 fuzzy。",
      "4. 如果返回 matchStatus=fuzzy_candidates，最终必须说明：当前 Metapi 没有后端精确查询 API，这是基于 GET /api/models/marketplace 全量数据的本地模糊候选。",
      "5. 如果返回 matchStatus=not_found，建议检查模型 ID 拼写，或 refresh=true 刷新后重试。",
      "6. 输出站点名、站点 URL、命中模型值、置信度；不要把 fuzzy 候选说成权威精确结果。",
      "长期 API 建议：GET /api/models/marketplace?model=<modelId> 或 GET /api/models/:modelId/sites，由后端基于规范模型 ID 精确查询。",
    ].join("\n"),
  },
  {
    id: "start_all_checkin",
    title: "开始签到",
    description: "触发 Metapi 全部签到任务，并读取签到日志汇总成功/失败/跳过。",
    tags: ["Metapi", "签到", "checkin", "巡检"],
    source: "skill",
    defaultEnabled: true,
    risk: "medium",
    recommendedCapabilities: ["deliver_result"],
    selectionHints: ["开始签到", "全部签到", "启动签到", "签到巡检", "checkin"],
    prompt: [
      "任务策略：开始签到（全部）",
      "目标：调用 Metapi 管理 API 启动全部签到，并汇总结果。",
      "硬性边界：",
      "1. 签到触发与日志一律使用 metapi_* 本地 API 工具（后台 fetch）。禁止浏览器去请求 127.0.0.1:4000。",
      "2. 本策略不要求浏览器操作页面；浏览器补签由 /补签 策略处理。",
      "3. 禁止触发后每隔几秒疯狂轮询日志。等待应交给 metapi_trigger_checkin 的 waitSeconds 内部轮询。",
      "执行顺序：",
      "1) 若未配置管理令牌，先提示配置或调用 metapi_configure。",
      "2) 只调用一次 metapi_trigger_checkin(waitSeconds=60~120, pollIntervalSeconds=5)。",
      "   该工具会像任务 runner 一样在工具内部等待/轮询，并返回 newLogCount 与 summary。",
      "3) 若 trigger 返回已有 summary/newLogCount>0：直接据此汇报，不要马上再连打 get/summarize。",
      "4) 若仍 pending/newLogCount=0：最多再调用 1 次 metapi_trigger_checkin(waitSeconds=60) 或 1 次 metapi_summarize_checkin_logs；不要短间隔连刷。",
      "5) 输出清晰分组：success / failed / skipped / other，以及 repairCandidates。",
      "6) 若任务仍在进行，明确告诉用户“仍在跑，可稍后 /补签 或再查日志”，然后结束。",
      "7) 最终不要回显 token/密钥。",
    ].join("\n"),
  },
  {
    id: "repair_failed_checkin",
    title: "补签",
    description: "根据签到日志找出失败/跳过站点，优先打开外部签到URL或控制台/个人资料，自行完成登录与签到。",
    tags: ["Metapi", "补签", "浏览器", "签到失败"],
    source: "skill",
    defaultEnabled: true,
    risk: "high",
    recommendedCapabilities: ["observe_page", "operate_page", "deliver_result"],
    selectionHints: ["补签", "签到失败", "跳过补签", "手动签到", "repair checkin"],
    prompt: [
      "任务策略：补签（失败/跳过）——必须打开站点找签到入口",
      "目标：对 Metapi 日志 failed/skipped 站，用浏览器真正打开页面并完成签到。",
      "绝对禁止：",
      "1. 禁止只读日志后总结就结束。",
      "2. 禁止因官方日志 HTTP404/fetch failed/签到未启用/Cloudflare403 就不打开。",
      "3. 禁止对未打开的站下结论。",
      "4. 禁止在 needs_human（验证码人工）时 close_page 关掉该标签；应保留页面给用户，立刻继续下一站。",
      "打开哪个 URL：",
      "- 优先 openUrl = externalCheckinUrl（站点已配置的外部签到站）",
      "- 没有外部签到站时再用 siteUrl 根站",
      "- 示例：new-api.abrdns.com → checkin.new-api.abrdns.com；x666.me → up.x666.me",
      "登录规则：",
      "- 若页面未登录/login/expired：优先点击 LinuxDO / Linux.do 登录",
      "- 进入 LINUX DO Connect 授权页后，必须立刻点击黑色大按钮「允许」，不要停在授权页",
      "- 其次 GitHub 登录；GitHub 授权页同样点 Authorize/允许",
      "- 完成 OAuth/回调回到站点后，再继续找签到入口",
      "签到入口搜索顺序（必须按序找，找不到才判无签到）：",
      "1) 外部签到页本体（今日签到/立即签到/领取奖励）",
      "2) 控制台 → 个人中心/个人资料/个人设置 → 每日签到/立即签到",
      "3) 控制台 → 钱包/余额/充值/topup/wallet 页面内是否有「每日签到/签到奖励」入口（有些站把签到放在钱包）",
      "4) 主页/首页/仪表盘 hero 区、公告区、卡片区找签到",
      "5) 顶栏/侧栏/标签栏/导航：签到、福利、奖励中心、任务与奖励、每日簽到",
      "6) 以上都没有：record status=failed message=未找到签到入口，继续下一站",
      "验证码（硬规则）：",
      "A. 普通图形验证码：仅当模型支持视觉时才 screenshot 识图；否则 needs_human，保留页面，立刻下一站。",
      "B. SHIELD/我不是机器人复选框（同源，非跨域 iframe）：click 复选框本体。",
      "C. hCaptcha 图片题 / 点选图：一旦出现「图片挑战/点选/拖动」类题目，立刻 needs_human，禁止反复截图重试；保留标签页，继续其他站。",
      "D. Cloudflare Turnstile checkbox/managed（含「请验证您是真人」iframe）：",
      "   1) take_snapshot 找 role=Iframe 且 name/src 含 turnstile / challenges.cloudflare.com / 请验证 的 UID",
      "   2) click 该 iframe UID（CDP 真实鼠标可进入跨域 frame；禁止指望宿主页 JS .click）",
      "   3) wait_for 或 wait 2~8s 后再 take_snapshot；若已通过/签到成功继续",
      "   4) 若变成图片点选/拖动，或 click 后仍「验证码校验超时/请验证您是真人」：立刻 needs_human，保留页面，继续其他站",
      "   5) 禁止伪造 cf-turnstile-response token；不要对同一 iframe 空转超过 2 次",
      "立即签到后的快失败/诊断：",
      "1) 点击「立即签到」后（或点击「今日签到」/「领取奖励」后），先 wait_for 成功/已签到/错误/失败/请先登录/验证等关键文本 2~5 秒，或用 click includeSnapshot / take_snapshot 立刻确认页面变化；不要一上来长时间等 network_idle。",
      "2) 成功判据必须是明确成功/已签到文本、按钮变成已签到/disabled、余额/日历/积分变化，或相关签到接口成功；点击工具返回成功不等于签到成功。",
      "3) 若按钮仍在、出现「错误」/失败 toast、余额或日历没有变化，立刻 collect_diagnostics，并用 network_list_requests 定位最近的 signin/checkin/reward/user 相关 POST/fetch，再按请求 ID 调 network_get_request_details 读取脱敏详情；把状态码、接口错误文案、Console 摘要写入 metapi_record_browser_checkin message。",
      "4) 不要反复点击同一个签到入口：普通点击最多 1 次；仅在 UID 过期/遮挡等真实点击失败时，重新 take_snapshot 后再试 1 次；页面或后端已经返回错误时直接 record status=failed。",
      "执行：",
      "1) metapi_summarize_checkin_logs 取 mustOpenThisRound",
      "2) 每个候选必须 new_page(openUrl)（不要每次都 includeSnapshot）",
      "3) take_snapshot 定位；登录 → 按入口搜索顺序找签到 → click",
      "4) 成功/失败/无入口：close_page + metapi_record_browser_checkin(siteUrl,status必填,message)",
      "5) needs_human：不要 close_page；只 record + 切到下一站",
      "6) 有候选时至少 1 次 new_page 才允许最终总结",
      "7) 最终分 openedAndProcessed / pendingNextBatch，禁止把 pending 写成 failed",
      "8) 浏览器补签不改写 Metapi 官方日志",
      "9) 需要删除站点用 metapi_delete_site；需要关闭站点签到用 metapi_set_site_checkin_enabled",
    ].join("\n"),
  },
];
