declare module "*.mjs" {
  const value: any;
  export default value;
  export const AI_CONFIG_STATES: any;
  export const AI_PROTOCOL_TYPES: any;
  export const DEFAULT_SEARCH_TARGET_ID: string;
  export const SEARCH_TARGETS: any[];
  export const DEFAULT_TODO_FILTER: string;
  export const DEFAULT_TODO_PRIORITY: string;
  export const TODO_FILTERS: Record<string, string>;
  export const TODO_PRIORITIES: Record<string, string>;
  export const TODO_FILTER_LABELS: Record<string, string>;
  export const TODO_PRIORITY_LABELS: Record<string, string>;
  export const TODO_STORAGE_VERSION: number;
  export const WIDGET_LAYOUT_STORAGE_KEY: string;
  export const WIDGET_STAGE_TRANSFORM_PREF: string;
  export function addTask(...args: any[]): any;
  export function buildAiSearchPreview(...args: any[]): any;
  export function buildAiTestRequest(...args: any[]): any;
  export function clearCompletedTasks(...args: any[]): any;
  export function createAiPreviewService(...args: any[]): any;
  export function createDefaultWidgetLayout(...args: any[]): any;
  export function createLocalSuggestionItems(...args: any[]): any[];
  export function deleteTask(...args: any[]): any;
  export function ensureOriginPermission(...args: any[]): Promise<any>;
  export function fetchRemoteSuggestionItems(...args: any[]): Promise<any>;
  export function fetchWithTimeout(...args: any[]): Promise<any>;
  export function getStoredAiConfigState(...args: any[]): Promise<any>;
  export function getStoredSearchSettings(...args: any[]): Promise<any>;
  export function getTodayDateString(...args: any[]): string;
  export function getVisibleTasks(...args: any[]): any[];
  export function hideWidget(...args: any[]): Promise<any>;
  export function isChatCompletionsEndpoint(...args: any[]): boolean;
  export function isTaskOverdue(...args: any[]): boolean;
  export function loadWidgetLayout(...args: any[]): Promise<any>;
  export function mergeSuggestionItems(...args: any[]): any[];
  export function normalizeAiRuntimeError(...args: any[]): any;
  export function normalizeFilter(...args: any[]): string;
  export function normalizeSearchDecision(...args: any[]): any;
  export function normalizeTextValue(...args: any[]): string;
  export function normalizeTaskPayload(...args: any[]): any;
  export function normalizeWidgetLayout(...args: any[]): any;
  export function parseAiRuntimeResponse(...args: any[]): any;
  export function readSearchHistory(...args: any[]): Promise<any[]>;
  export function readTodoPayload(...args: any[]): Promise<any>;
  export function resolveChatCompletionsEndpoint(...args: any[]): string;
  export function resolveDirectNavigationTarget(...args: any[]): string;
  export function resolveOriginPattern(...args: any[]): string;
  export function resolveOriginPatternSafely(...args: any[]): string;
  export function restoreWidget(...args: any[]): Promise<any>;
  export function runPageTransition(...args: any[]): Promise<void>;
  export function saveSearchHistoryEntry(...args: any[]): Promise<any[]>;
  export function saveStoredAiConfigState(...args: any[]): Promise<any>;
  export function saveStoredSearchSettings(...args: any[]): Promise<void>;
  export function saveWidgetLayout(...args: any[]): Promise<any>;
  export function sanitizeStageTransform(...args: any[]): any;
  export function updateTask(...args: any[]): any[];
  export function updateWidgetPrefs(...args: any[]): Promise<any>;
  export function writeTodoPayload(...args: any[]): Promise<any>;
}
